# Consolidated air data estimates

float32 EAS_ms			# Equivalent airpeed (m/s)
float32 EAS_accuracy_ms		# Equivalent airpeed 1-Sigma accuracy (m/s)
float32 TAS_ms			# True airpeed (m/s)
float32 TAS_accuracy_ms		# True airpeed 1-Sigma accuracy (m/s)
float32 AoA_rad			# Angle of attack (rad)
float32 AoA_accuracy_rad	# Angle of attack 1-Sigma accuracy (rad)
float32 AoS_rad			# Angle of sideslip (rad)
float32 AoS_accuracy_rad	# Angle of sideslip 1-Sigma accuracy (rad)
