# WINGTRA: this msg file has been modified to fit our PP needs, so most things will have comments related to topic metadata

uint64 timestamp			# time since system start (microseconds)

float32[3] magnetometer_ga		# DESCRIPTION: "Magnetic field in XYZ body frame, in Gauss"

bool mag_sample_sane			# WINGTRA: DESCRIPTION: "True if no mag jump is detected or timeout"

float32 magnetometer_temp 	 	# WINGTRA: DESCRIPTION: "Temperature in degrees Celsius"
